DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  info_type: "discrete"
  g_info_injection: "cBN"
  info_num_discrete_c: 1
  info_dim_discrete_c: 10
LOSS:
  infoGAN_loss_discrete_lambda: 1.0
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
