DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_d_sn: True
LOSS:
  adv_loss: "hinge"
AUG:
  apply_diffaug: True
  diffaug_type: "diffaug"
OPTIMIZATION:
  total_steps: 200000
