DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_d_sn: True
  info_type: "discrete"
  g_info_injection: "cBN"
  info_num_discrete_c: 1
  info_dim_discrete_c: 10
LOSS:
  adv_loss: "hinge"
  infoGAN_loss_discrete_lambda: 1.0
