DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_d_sn: True
LOSS:
  adv_loss: "hinge"
AUG:
  apply_apa: True
  apa_initial_augment_p: 0
  apa_target: 0.6
  apa_kimg: 500
  apa_interval: 4
OPTIMIZATION:
  total_steps: 200000
