DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "stylegan2"
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  g_act_fn: "Auto"
  d_act_fn: "Auto"
  z_prior: "gaussian"
  z_dim: 512
  w_dim: 512
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  apply_g_ema: True
  info_type: "discrete"
  g_info_injection: "concat"
  info_num_discrete_c: 1
  info_dim_discrete_c: 10
LOSS:
  adv_loss: "logistic"
  apply_r1_reg: True
  r1_lambda: 0.01
  r1_place: "outside_loop"
  infoGAN_loss_discrete_lambda: 1.0
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  g_lr: 0.0025
  d_lr: 0.0025
  beta1: 0
  beta2: 0.99
  d_first: False
  g_updates_per_step: 1
  d_updates_per_step: 1
  total_steps: 200000
STYLEGAN:
  g_reg_interval: 4
  d_reg_interval: 16
  mapping_network: 2
  style_mixing_p: 0.0
  g_ema_kimg: 500
  g_ema_rampup: 0.05
  apply_pl_reg: False
  pl_weight: 0
  d_architecture: "orig"
  d_epilogue_mbstd_group_size: 32
