DATA:
  name: "ImageNet"
  img_size: 128
  num_classes: 1000
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_d_sn: True
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 500000
