DATA:
  name: "CIFAR100"
  img_size: 32
  num_classes: 100
MODEL:
  backbone: "big_resnet_deep_legacy"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [2]
  attn_d_loc: [1]
  z_dim: 128
  g_shared_dim: 128
  g_conv_dim: 128
  d_conv_dim: 128
  g_depth: 2
  d_depth: 2
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 64
  g_lr: 0.0002
  d_lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  d_updates_per_step: 5
  total_steps: 100000
