DATA:
  name: "FFHQ"
  img_size: 1024
  num_classes: 1
MODEL:
  backbone: "stylegan2"
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  g_act_fn: "Auto"
  d_act_fn: "Auto"
  z_prior: "gaussian"
  z_dim: 512
  w_dim: 512
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  apply_g_ema: True
LOSS:
  adv_loss: "logistic"
  apply_r1_reg: True
  r1_lambda: 2
  r1_place: "outside_loop"
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  batch_size: 32
  acml_steps: 1
  g_lr: 0.002
  d_lr: 0.002
  beta1: 0
  beta2: 0.99
  d_first: False
  g_updates_per_step: 1
  d_updates_per_step: 1
  total_steps: 800000
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.6
  ada_kimg: 500
  ada_interval: 4
STYLEGAN:
  g_reg_interval: 4
  d_reg_interval: 16
  mapping_network: 8
  style_mixing_p: 0.9
  g_ema_kimg: 10
  g_ema_rampup: "N/A"
  apply_pl_reg: True
  pl_weight: 2
  d_architecture: "resnet"
  d_epilogue_mbstd_group_size: 4
